name: Build

on:
  push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: temurin

    - name: Run Maven
      run: mvn -B clean verify -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: bundles
        path: |
            ch.sbb.scion.rcp.microfrontend/target/*.jar
            ch.sbb.scion.rcp.workbench/target/*.jar