name: Build

on:
  push

env:
  LOMBOK_VERSION: 1.18.26

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    
    - name: 'Install Edge'
      uses: browser-actions/setup-edge@v1

    - name: 'Checkout'
      uses: actions/checkout@v3

    - name: 'Setup JDK'
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin
        gpg-private-key: "${{ secrets.GPG_PRIVATE_KEY }}"
        gpg-passphrase: GPG_PASSPHRASE # This is actually the default value
        
    - name: 'Setup Lombok'
      run: |
        mvn -B dependency:copy -Dartifact=org.projectlombok:lombok:$LOMBOK_VERSION:jar -DoutputDirectory=. -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
        echo "lombok=lombok-$LOMBOK_VERSION.jar" >> "$GITHUB_ENV"

    - name: 'Run Maven'
      run: mvn -B clean verify -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
      env:
        GPG_PASSPHRASE: "${{ secrets.GPG_PASSPHRASE }}"
        MAVEN_OPTS: "-javaagent:${{ env.lombok }}"
      
    - name: 'Upload microfrontend library'
      uses: actions/upload-artifact@v3
      with:
        name: microfrontend-library
        path: | 
          ch.sbb.scion.rcp.microfrontend/target/*.jar
          ch.sbb.scion.rcp.microfrontend/target/*.jar.asc

    - name: 'Upload workbench library'
      uses: actions/upload-artifact@v3
      with:
        name: workbench-library
        path: |
          ch.sbb.scion.rcp.workbench/target/*.jar
          ch.sbb.scion.rcp.workbench/target/*.jar.asc
        
#    - name: 'Run headless SWTBot Tests'    
#      run: |
#        sudo apt-get install libwebkit2gtk-4.0-37
#        xvfb-run java -Xms256M -Xmx768M -jar ch.sbb.scion.rcp.microfrontend.e3.app.demo.product/target/products/ch.sbb.scion.rcp.microfrontend.e3.app.demo.product/linux/gtk/x86_64/plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar -application org.eclipse.swtbot.eclipse.junit5.headless.swtbottestapplication -product ch.sbb.scion.rcp.microfrontend.e3.app.demo.product -testApplication ch.sbb.scion.rcp.microfrontend.e3.app.demo.application -data . -testPluginName ch.sbb.scion.rcp.microfrontend.e3.app.demo.test formatter=org.apache.tools.ant.taskdefs.optional.junit.XMLJUnitResultFormatter,./AllTests.xml -classname ch.sbb.scion.rcp.microfrontend.e3.app.demo.test.PopupCapabilityTest -os linux -ws gtk -arch x86_64 -consoleLog -debug
